2023-04-30 22:58:58,313 - __init__.py:init_device[line:18] - CRITICAL: 初始化网关设备驱动 start...
2023-04-30 22:58:58,327 - device_manager.py:open[line:64] - INFO: SUCCESS : open device设备('水声通信机0')
2023-04-30 22:58:58,327 - core_scheduling.py:init_device_list_threadhandle[line:51] - INFO: 设备列表中存在1个设备, 设备0=设备('水声通信机0')
2023-04-30 22:58:58,336 - connection_workflow.py:start[line:179] - INFO: Pika version 1.3.1 connecting to ('::1', 5672, 0, 0)
2023-04-30 22:58:58,337 - io_services_utils.py:_on_writable[line:345] - INFO: Socket connected: <socket.socket fd=1292, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 7841, 0, 0), raddr=('::1', 5672, 0, 0)>
2023-04-30 22:58:58,350 - connection_workflow.py:_on_transport_establishment_done[line:428] - INFO: Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000025B811B9580>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000025B811B9580> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2023-04-30 22:58:58,357 - connection_workflow.py:_report_completion_and_cleanup[line:293] - INFO: AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000025B811B9580> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2023-04-30 22:58:58,357 - connection_workflow.py:_report_completion_and_cleanup[line:725] - INFO: AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000025B811B9580> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2023-04-30 22:58:58,357 - blocking_connection.py:_create_connection[line:453] - INFO: Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x0000025B811B9580> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2023-04-30 22:58:58,359 - blocking_connection.py:__init__[line:1264] - INFO: Created channel=1
2023-04-30 22:58:58,363 - core_scheduling.py:monitor_web_task_threadhandle[line:216] - CRITICAL: SUCCESS : Create Pika server.
2023-04-30 22:59:07,341 - bsp_underwater_acoustic_comm.py:_read_bytes[line:209] - CRITICAL: 水声通信设备(端口'COM5' 状态True) 接收到一帧数据b'U\xaa6\x01fiieaaaaQreceived\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\r\n'
2023-04-30 22:59:07,345 - bsp_underwater_acoustic_comm.py:_write_bytes[line:185] - CRITICAL: 水声通信设备(端口'COM5' 状态True)传输一帧数据b'U\xaa6\x04filename_received\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\r\n'
2023-04-30 22:59:13,767 - bsp_underwater_acoustic_comm.py:_write_bytes[line:190] - WARNING: 水声通信设备(端口'COM5' 状态True) 发送数据时接收到0X66 0XBB确认回馈
2023-04-30 22:59:13,782 - device_manager.py:read[line:110] - INFO: 设备('水声通信机0')没有数据可读
2023-04-30 22:59:37,285 - core_scheduling.py:deal_data_forwarding_processhandle[line:106] - ERROR: ERROR   : 线程池处理DIRECT_DEVICE_TO_FILE任务124440
2023-04-30 22:59:37,286 - bsp_underwater_acoustic_comm.py:_read_bytes[line:209] - CRITICAL: 水声通信设备(端口'COM5' 状态True) 接收到一帧数据b'U\xaa6\x02123\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\r\n'
2023-04-30 22:59:37,290 - core_scheduling.py:deal_data_forwarding_callback[line:159] - ERROR: 线程池处理任务124440回调出现错误, 错误原因(sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 4108 and this is thread id 6948.
[SQL: SELECT tasks.task_id AS tasks_task_id, tasks.task_name AS tasks_task_name, tasks.task_priority AS tasks_task_priority, tasks.source_file_id AS tasks_source_file_id, tasks.source_file_name AS tasks_source_file_name, tasks.source_file_size AS tasks_source_file_size, tasks.source_file_path AS tasks_source_file_path, tasks.target_device_id AS tasks_target_device_id, tasks.target_device_name AS tasks_target_device_name, tasks.task_status AS tasks_task_status, tasks.task_submit_time AS tasks_task_submit_time, tasks.task_submit_source AS tasks_task_submit_source, tasks.task_execute_time AS tasks_task_execute_time, tasks.task_finish_time AS tasks_task_finish_time, tasks.task_transfer_speed AS tasks_task_transfer_speed 
FROM tasks 
WHERE tasks.task_id = ?
 LIMIT ? OFFSET ?]
[parameters: [{}]]
(Background on this error at: https://sqlalche.me/e/14/f405)
2023-04-30 22:59:37,294 - bsp_underwater_acoustic_comm.py:_write_bytes[line:185] - CRITICAL: 水声通信设备(端口'COM5' 状态True)传输一帧数据b'U\xaa6\x04filesize_received\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\r\n'
2023-04-30 22:59:37,337 - device_manager.py:read[line:110] - INFO: 设备('水声通信机0')没有数据可读
2023-04-30 22:59:37,338 - core_scheduling.py:deal_data_forwarding_processhandle[line:106] - ERROR: ERROR   : 线程池处理DIRECT_DEVICE_TO_FILE任务124441
2023-04-30 22:59:37,339 - core_scheduling.py:deal_data_forwarding_callback[line:159] - ERROR: 线程池处理任务124441回调出现错误, 错误原因(sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 4108 and this is thread id 6948.
[SQL: SELECT tasks.task_id AS tasks_task_id, tasks.task_name AS tasks_task_name, tasks.task_priority AS tasks_task_priority, tasks.source_file_id AS tasks_source_file_id, tasks.source_file_name AS tasks_source_file_name, tasks.source_file_size AS tasks_source_file_size, tasks.source_file_path AS tasks_source_file_path, tasks.target_device_id AS tasks_target_device_id, tasks.target_device_name AS tasks_target_device_name, tasks.task_status AS tasks_task_status, tasks.task_submit_time AS tasks_task_submit_time, tasks.task_submit_source AS tasks_task_submit_source, tasks.task_execute_time AS tasks_task_execute_time, tasks.task_finish_time AS tasks_task_finish_time, tasks.task_transfer_speed AS tasks_task_transfer_speed 
FROM tasks 
WHERE tasks.task_id = ?
 LIMIT ? OFFSET ?]
[parameters: [{}]]
(Background on this error at: https://sqlalche.me/e/14/f405)
